import Head from "next/head";
import type { NextPage } from "next";
// import { useConnect } from "wagmi";

// import { Connect, Disconnect, SwitchNetwork } from "@/components/wallet";

// import { useNetwork } from "wagmi";
// import { NETWORK_ID } from "@/config";

const CreateServicePage: NextPage = () => {
  //   const { activeChain } = useNetwork();
  //   const { activeConnector } = useConnect();

  return (
    <div className={""}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Create Service Page</h1>
      </main>
    </div>
  );
};

export default CreateServicePage;
