import Head from "next/head";
import { useRouter } from "next/router";
import type { NextPage } from "next";
// import { useConnect } from "wagmi";

// import { Connect, Disconnect, SwitchNetwork } from "@/components/wallet";

// import { useNetwork } from "wagmi";
// import { NETWORK_ID } from "@/config";

const MultisigPage: NextPage = () => {
  const router = useRouter();
  const { address } = router.query;
  //   const { activeChain } = useNetwork();
  //   const { activeConnector } = useConnect();

  return (
    <div className={""}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Multisig</h1>
        <div>Contract address: {address}</div>
      </main>
    </div>
  );
};

export default MultisigPage;
